[workspace]
members = [
    'qmetaobject',
    'qmetaobject_impl',
    'qttypes',

    'examples/graph',
    'examples/qmlextensionplugins',
    'examples/todos',
    'examples/webengine',
    'examples/qenum',
    'examples/nested_qobjects',
]
