[package]
name = "qmlextensionplugins"
version = "0.1.0"
edition = "2018"
authors = ["Olivier Goffart <ogoffart@woboq.com>"]

[lib]
name = "qmlqtimeexampleplugin"
crate-type = ["dylib"]

[dependencies]
qmetaobject = { path = "../../qmetaobject"}
chrono = "^0.4"
